simplesocial/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts import views

app_name = 'accounts'

urlpatterns = [
        path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
        path('logout/',auth_views.LogoutView.as_view(),name='logout'),
        path('signup/',views.SignUp.as_view(),name='signup'),
        path('search/',views.Search.as_view(),name='search'),
    ]

simplesocial/posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<username>/",views.UserPosts.as_view(),name="for_user"),
    path("by/<username>/<int:pk>/",views.PostDetail.as_view(),name="single"),
    path("delete/<int:pk>/",views.DeletePost.as_view(),name="delete"),
]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',views.HomePage.as_view(),name='home'),
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')), #For registration login and logout
    path('welcome/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('groups/',include('groups.urls',namespace='groups')),
    path('posts/',include('posts.urls',namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplesocial/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Star Social</title>

    {# bootstrap #}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    {# googlefonts #}
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,600;0,700;1,700&display=swap" rel="stylesheet">

    {# googlefonts navbar #}
    <link href="https://fonts.googleapis.com/css2?family=Unica+One&display=swap" rel="stylesheet">

    {# Custom Css #}
    <link rel="stylesheet" href="{% static "css/master.css" %}">
    <link rel="stylesheet" href="{% static "css/base.css" %}">

    {# Font Awesome #}
    <script src="https://kit.fontawesome.com/56c14be9a2.js" crossorigin="anonymous"></script>

    {% block head %}

    {% endblock %}

  </head>
  <body class="large-header demo">

    <nav class="navbar navbar-expand-lg bg-light mynav navcss " role=navigation>
      <div class="container">

          <a class="navbar-brand mynav navb align-items-center tc2" href="{% url 'home' %}">Star Social</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#hamburger" aria-controls="hamburger" aria-expanded="false" aria-label="Toggle navigation">
            <span style="color:white" class="fas fa-bars"></span>
          </button>

        <div class="collapse navbar-collapse" id=hamburger>
          <div class="navbar-nav ml-auto">

            {% if user.is_authenticated %}
              <a class="nav-item nav-link tc2" href="{% url 'posts:create' %}" class="btn btn-simple"><i class="fas fa-plus"></i> Post</a>
              <a class="nav-item nav-link tc2" href="{% url 'groups:all' %}" class="btn btn-simple">Groups</a>
              <a class="nav-item nav-link tc2" href="{% url 'groups:create' %}" class="btn btn-simple">Create Group</a>
              <a class="nav-item nav-link tc2" href="{% url 'accounts:logout' %}" class="btn btn-simple">Log Out</a>
            {% else %}
              <a class="nav-item nav-link tc2" href="{% url 'groups:all' %}" class="btn btn-simple">Groups</a>
              <a class="nav-item nav-link tc2" href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a>
              <a class="nav-item nav-link tc2" href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign Up</a>
            {% endif %}

            <form method="GET" action="{% url 'accounts:search' %}" class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="search" placeholder="Search groups" aria-label="Search" id="query" name="query" value="{{ request.GET.query }}">
              <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
            </form>

          </div>


        </div>

<!-- Removed search from here and shifted above -->

      </div>
    </nav>
    <br>
    <div class="full-body tc">
      <div class="container ">

        {% block content %}

        {% endblock %}

        <div id="large-header" class="">
          <canvas id="demo-canvas"></canvas>
        </div>
      </div>
    </div>


      <br>
      <br>
      <br>

      {# search js value keeper  #}

      {# <script type="text/javascript">
        document.getElementById("search").value = "{{ query }}"
      </script> #}

    {# custom js #}

	<script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/499416/TweenLite.min.js" type="text/javascript" ></script>
	<script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/499416/EasePack.min.js" type="text/javascript" ></script>
	<script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/499416/demo.js" type="text/javascript" ></script>

    {# custom js #}
    <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script>

    {# bootstrap js #}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

  </body>
</html>

simplesocial/templates/index.html
{% extends 'base.html' %}
{% block head %}
{# {% load static %} #}

{# Custom Css #}
{# <link rel="stylesheet" href="{% static "css/master.css" %}"> #}

{% endblock %}
{% block content %}
<div class="colourful container d-flex justify-content-center">
  <svg viewBox="0 0 600 300">
    <!-- Symbol-->
    <symbol id="s-text">
      <text text-anchor="middle" x="50%" y="50%" dy=".35em">Star Social</text>
    </symbol>
    <!-- Duplicate symbols-->
    <use class="text" xlink:href="#s-text"></use>
    <use class="text" xlink:href="#s-text"></use>
    <use class="text" xlink:href="#s-text"></use>
    <use class="text" xlink:href="#s-text"></use>
    <use class="text" xlink:href="#s-text"></use>
  </svg>
</div>

{% endblock %}

simplesocial/templates/test.html
{% extends "base.html" %}
{% block content %}
    <h1 class="tc">You are now logged in!</h1>
{% endblock %}

simplesocial/templates/thanks.html
{% extends "base.html" %}
{% block content %}
    <h1 class="tc">Thanks for visiting, comeback soon!</h1>
{% endblock %}