simplesocial/groups/urls.py
# groups urls.py
from django.urls import path
from groups import views

app_name = 'groups'

urlpatterns = [
    path('',views.ListGroup.as_view(),name='all'),
    path('new/',views.CreateGroup.as_view(),name='create'),
    path('posts/in/<slug>/',views.SingleGroup.as_view(),name='single'),
    path('join/<slug>/',views.JoinGroup.as_view(),name='join'),
    path('leave/<slug>/',views.LeaveGroup.as_view(),name='leave'),
]

simplesocial/posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<username>/",views.UserPosts.as_view(),name="for_user"),
    path("by/<username>/<int:pk>/",views.PostDetail.as_view(),name="single"),
    path("delete/<int:pk>/",views.DeletePost.as_view(),name="delete"),
]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',views.HomePage.as_view(),name='home'),
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')), #For registration login and logout
    path('welcome/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('groups/',include('groups.urls',namespace='groups')),
    path('posts/',include('posts.urls',namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplesocial/groups/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse

import misaka

from django.contrib.auth import get_user_model
User = get_user_model()

from django import template
register = template.Library()
# Create your models here.

class Group(models.Model):
    name = models.CharField(max_length=256,unique=True)
    slug = models.SlugField(allow_unicode=True,unique=True)
    description = models.TextField(blank=True,default='')
    description_html = models.TextField(editable=False,blank=True)
    created_at = models.DateTimeField(auto_now=True)
    members = models.ManyToManyField(User,through="GroupMember")

    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug=slugify(self.name)
        self.description_html=misaka.html(self.description)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('groups:single',kwargs={'slug':self.slug})

    class Meta():
        ordering = ['-created_at']

class GroupMember(models.Model):
    group = models.ForeignKey(Group,related_name='memberships',on_delete=models.CASCADE)
    user = models.ForeignKey(User,related_name='user_groups',on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta():
        unique_together=['group','user']

simplesocial/groups/views.py
from django.shortcuts import render,get_object_or_404
from django.contrib import messages
# Create your views here.
from  django.contrib.auth.mixins import(LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.urls import reverse
from django.views import generic
from groups.models import Group,GroupMember

from . import models

class CreateGroup(LoginRequiredMixin,generic.CreateView):
    fields = ('name','description')
    model = Group

#single group detail viewing page view
class SingleGroup(generic.DetailView):
    model = Group

class ListGroup(generic.ListView):
    model = Group
    paginate_by = 8

class JoinGroup(LoginRequiredMixin,generic.RedirectView):

    def get_redirect_url(self,*args,**kwargs):
        return reverse("groups:single",kwargs={'slug':self.kwargs.get('slug')})

    def get(self,request,*args,**kwargs):
        group = get_object_or_404(Group,slug=kwargs.get('slug'))

        try:
            GroupMember.objects.create(user=self.request.user,group=group)
        except IntegrityError:
            messages.warning(self.request,'Warning already a member!')
        else:
            messages.success(self.request,'You are a member now!')

        return super().get(request,*args,**kwargs)

class LeaveGroup(LoginRequiredMixin,generic.RedirectView):

    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})

    def get(self,request,*args,**kwargs):

        try:
            membership = models.GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get('slug')
            ).get()
        except models.GroupMember.DoesNotExist:
            messages.danger(self.request,'Sorry you are not in this group!')
        else:
            membership.delete()
            messages.warning(self.request,'You have left the group!')
        return super().get(request,*args,**kwargs)

simplesocial/groups/templates/groups/group_base.html
{% extends "base.html" %}
{% block content %}

<div class="container tc">
  <div class="row">

    {% block pregroup %}{% endblock %}
    {% block group_content %}{% endblock %}
    {% block postgroup %}{% endblock %}

  </div>
</div>

{% endblock %}

simplesocial/groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}
{% block pregroup %}
<div class="container">

  <h1>{{ group.name }}</h1>
  <h2>Member Count: {{ group.members.count }}</h2>

  <div class="content">

    {% if user in group.members.all %}

      <a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-lg btn-fill btn-outline-warning">
        <span class="fa fa-times-circle-o"> Leave</span>
      </a>
<br><br>
    {% else %}

    <a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-lg btn-fill btn-outline-success">
      <span class="fa fa-check-circle-o"> Join</span>
    </a>
<br><br>
    {% endif %}

    {% if messages %}
      <ul class="messages">
        {% for message in messages %}
        {# use alert- or text- #}
          <li{% if message.tags %} class="alert-{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
      </ul>
    {% endif %}

  </div>

</div>
{% endblock %}

{% block group_content %}

  <div class="col-md-8">
    {% if group.posts.count == 0 %}
      <h2>No posts in this group yet!</h2>
    {% else %}
      {% for post in group.posts.all  %}
        {% include "posts/_post.html" %}

      <br><br>
      {% endfor %}
    {% endif %}

  </div>

{% endblock %}

simplesocial/groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap4 %}
{% block group_content %}
<div class="container">

  <h4>Create a new group!</h4>

    <form action="{% url "groups:create" %}" method="post" id='groupForm'>
      {% csrf_token %}
      {% bootstrap_form form %}
      <input class="btn btn-outline-primary btn-lg" type="submit" value="Create">
    </form>

</div>

{% endblock %}

simplesocial/groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}
{% load static %}
{% block pregroup %}

  <div class="col-md-4">
    <div class="content">

      {% if user.is_authenticated %}

      <h2>Welcome Back!
        <a href="{% url 'posts:for_user' username=user.username %}">
          @{{ user.username }}
        </a>
      </h2>

      {% endif %}
      </div>

      <h2>Groups</h2>
      <p>Welcome to the groups page!</p>

      {% if user.is_authenticated %}

      <a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-outline-success">
        <span class="fa fa-plus">Create New Group!</span>
      </a>

      {% endif %}


  </div>

{% endblock %}

{% block group_content %}

<div class="col-md-8">
  <div class="list-group">
    {% for group in object_list %}
      <a href="{% url 'groups:single' slug=group.slug %}" class="list-group-item list-group-item-action flex-column align-items-start">
        <h3 class="tittle list-group-item-heading">{{ group.name }}</h3>
        <div class="list-group-item-text container-fluid">
          {{ group.description_html|safe }}
          <div class="row">
            <div class="col-md-4">
              <span class="badge badge-secondary">{{ group.members.count }}</span>
              member{{ group.members.count|pluralize }}
            </div>
            <div class="col-md-4">
              <span class="badge badge-secondary">{{ group.posts.count }}</span>
              post{{ group.posts.count|pluralize }}
            </div>
          </div>
        </div>

      </a>
    {% endfor %}

  </div>
</div>

{# Pagination #}

<div class="col-md-12">
  {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}

</div>




{% endblock %}